[package]
name = "fractal-explorer"
version = "0.1.0"
authors = ["Simon Schneemelcher <s.schneemelcher@tu-bs.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
